version: '3'

networks:
   nwtis_dz_2n:
     external:
        name: nwtis_dz_2n
       
volumes:
  nwtis_hsql_dz_2v:
     external: true
  nwtis_h2_dz_2v:
     external: true

services:
  nwtis_hsql_dz_2c:
     image: nwtis_hsql_dz_2i
     container_name: nwtis_hsql_dz_2c
     build:
        dockerfile: ./Dockerfile.hsql
     volumes:
     -  type: volume
        source: nwtis_hsql_dz_2v
        target: /usr/app/podaci
        volume:
           nocopy: true
     restart: unless-stopped
     networks:
        nwtis_dz_2n:
           ipv4_address: 20.24.5.3
  
  nwtis_h2_dz_2c:
      image: nwtis_h2_dz_2i
      container_name: nwtis_h2_dz_2c
      build:
         dockerfile: ./Dockerfile.h2
      volumes:
      -  type: volume
         source: nwtis_h2_dz_2v
         target: /usr/app/podaci
         volume:
            nocopy: true
      restart: unless-stopped
      networks:
        nwtis_dz_2n:
          ipv4_address: 20.24.5.4
  
  nwtis_servisi:
      image: nwtis_servisi
      container_name: nwtis_servisi
      build:
         dockerfile: ./Dockerfile.servisi
      restart: unless-stopped
      ports:
      -  9080:8080
      networks:
        nwtis_dz_2n:
          ipv4_address: 20.24.5.5
